### ISSUE TITLE
Cannot Install on Kali Linux

### ISSUE THREAD

**Issue by mangnik** [Karmaz95/crimson#5] opened 2023-09-18 04:36 UTC
Error: short-name "karmaz95/crimson:v3" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"

**Comment by Karmaz95** [comment] 2023-09-18 06:39
Hello, 

The issue is related to your specific docker configuration probably.
Based on your error message, it is something with the name resolving.

The image is publicly available here:
* https://hub.docker.com/layers/karmaz95/crimson/v3/images/sha256-61f9716111f33ef5283cfb3d6164dfac7456ea2bb1a5d3d1cd06973aea69e7be?context=repo

I just installed it on the latest Kali Linux version using:

```
docker pull karmaz95/crimson:v3
docker run -it karmaz95/crimson:v3
```

I would suggest to purge and reinstall docker.

In case you are using `podman`, this might be helpful:
* https://unix.stackexchange.com/questions/701784/podman-no-longer-searches-dockerhub-error-short-name-did-not-resolve-to-an
* https://github.com/containers/podman/issues/16096


You should change your configuration according to the above links to: 
```
cat .config/containers/registries.conf
unqualified-search-registries = ["docker.io"]
```

Let me know if this resolves the issue.

Best regards

**Comment by mangnik** [comment] 2023-09-18 07:34
Yeah you are right ..my conf were error

**Closed as completed** 2023-09-18 23:22 UTC
